version: "3.7"

services:
  gaia:
    build: .
    depends_on:
      - postgres
      - proxy
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gaia.rule=Host(`math.localhost`)"
      - "traefik.http.routers.gaia.entryPoints=web"
    stdin_open: true
    volumes:
      - .:/srv/gaia
      - type: tmpfs
        target: /srv/gaia/tmp/pids/

  webpacker:
    command: ./bin/webpack-dev-server
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    image: rails6-docker_gaia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webpacker.entryPoints=webpacker"
      - "traefik.http.routers.webpacker.rule=Host(`webpacker`)"
    volumes:
      - .:/srv/gaia

  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data

  proxy:
    image: traefik:2.0-alpine
    ports:
      - 80:80
      - 443:443
      - 3035:3035
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yml:/etc/traefik/traefik.yml

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./tmp/data/redis:/data
