---
version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
      - proxy
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/gaia?encoding=unicode&pool=5&timeout=5000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.app.headers.accessControlAllowMethods=GET,OPTIONS,PUT'
      - 'traefik.http.middlewares.app.headers.accessControlAllowOrigin=*'
      - 'traefik.http.middlewares.app.headers.accessControlMaxAge=100'
      - 'traefik.http.middlewares.app.headers.addVaryHeader=true'
      - 'traefik.http.routers.app.entryPoints=http'
      - 'traefik.http.routers.app.rule=Host(`gaia.localhost`)'
    stdin_open: true
    volumes:
      - .:/srv/gaia
      - /srv/gaia/node_modules
      - type: tmpfs
        target: /srv/gaia/tmp/pids/

  webpacker:
    command: ./bin/webpack-dev-server
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    image: gaia_app
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.webpacker.headers.accessControlAllowMethods=GET,OPTIONS,PUT'
      - 'traefik.http.middlewares.webpacker.headers.accessControlAllowOrigin=*'
      - 'traefik.http.middlewares.webpacker.headers.accessControlMaxAge=100'
      - 'traefik.http.middlewares.webpacker.headers.addVaryHeader=true'
      - 'traefik.http.routers.webpacker.entryPoints=webpacker'
    volumes:
      - .:/srv/gaia

  postgres:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:alpine
    restart: always
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data

  proxy:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 3035:3035
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yml:/etc/traefik/traefik.yml

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./tmp/data/redis:/data
